version: '3.3'

services:

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build: ./gpc
    restart: unless-stopped
    volumes:
      - static_value:/backend/static/django/
    depends_on:
      - db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/admin"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/django/
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/admin"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  static_value:
  postgres_value:
