# Generated by Django 4.1.7 on 2023-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.FloatField(verbose_name='Стоимость (RUB)'),
        ),
    ]
