# Generated by Django 4.1.7 on 2023-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_price_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_day',
            field=models.CharField(max_length=10, verbose_name='Срок поставки'),
        ),
    ]
